languages:
    Python: true
    JavaScript: true
exclude_paths:
  - "articles/migrations/*"
  - "blog/migrations/*"
  - "brainbank/migrations/*"
  - "lifeX/migrations/*"
  - "poems/migrations/*"
  - "sitedata/migrations/*"
  - "stories/migrations/*"
  - "friends/migrations/*"
