# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-28 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20160811_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='exclude_budgets',
            field=models.ManyToManyField(blank=True, related_name='exclude_budgets', to='finance.Budget'),
        ),
    ]
