# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-28 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_transaction_exclude_budgets'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('amount', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Loans & Credits',
                'ordering': ['name'],
                'verbose_name_plural': 'Loans & Credits',
            },
        ),
    ]
