# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brainbank', '0002_remove_brainbankpost_deliverable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brainbankpost',
            options={'verbose_name': 'BrainBank Post', 'verbose_name_plural': 'BrainBank Posts'},
        ),
    ]
