# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=256)),
                ('read', models.BooleanField(db_index=True, default=False)),
                ('liked', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'verbose_name_plural': 'Books',
                'ordering': ['title'],
                'verbose_name': 'Book',
            },
        ),
        migrations.CreateModel(
            name='BookList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=256)),
                ('slug', models.SlugField(max_length=256)),
                ('books', models.ManyToManyField(related_name='lists', to='hobbies.Book')),
            ],
            options={
                'verbose_name_plural': 'Book Lists',
                'ordering': ['title'],
                'verbose_name': 'Book List',
            },
        ),
        migrations.AlterField(
            model_name='movie',
            name='liked',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='seen',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
