# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0002_auto_20170923_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='hobbies.Book')),
            ],
            options={
                'verbose_name_plural': 'Book Annotations',
                'verbose_name': 'Book Annotation',
                'ordering': ['pk'],
            },
        ),
    ]
