# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-24 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0003_bookannotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklist',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='movielist',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
