# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-24 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0004_auto_20170924_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklist',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='lists', to='hobbies.Book'),
        ),
        migrations.AlterField(
            model_name='movielist',
            name='movies',
            field=models.ManyToManyField(blank=True, related_name='lists', to='hobbies.Movie'),
        ),
    ]
