# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-03 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sitebase', '0003_auto_20160214_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=128)),
                ('date_created', models.DateTimeField()),
                ('date_published', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='published')),
                ('short_description', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('body_type', models.CharField(choices=[('default', 'textarea'), ('html', 'html'), ('markdown', 'markdown')], default='markdown', max_length=8)),
                ('body_text', models.TextField(blank=True)),
                ('body', models.TextField()),
                ('authors', models.ManyToManyField(to='sitebase.Author')),
            ],
            options={
                'get_latest_by': 'date_published',
                'verbose_name': 'Journal Entry',
                'verbose_name_plural': 'Journal Entries',
                'ordering': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='JournalSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, unique=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('private', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Journal Section',
                'verbose_name_plural': 'Journal Sections',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JournalTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, unique=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Journal Tag',
                'verbose_name_plural': 'Journal Tags',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='journalentry',
            name='journal_tags',
            field=models.ManyToManyField(to='journal.JournalTag'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='journal.JournalSection'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='tags',
            field=models.ManyToManyField(to='sitebase.Tag'),
        ),
    ]
