# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-03 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='journal_tags',
            field=models.ManyToManyField(related_name='entries', to='journal.JournalTag'),
        ),
    ]
