# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-03 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_auto_20160503_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='private',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
