# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_journalentry_private'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('message', models.CharField(max_length=256)),
                ('public', models.BooleanField(default=False)),
                ('started_on', models.DateField()),
                ('total', models.PositiveSmallIntegerField(default=0)),
                ('current_length', models.PositiveSmallIntegerField(default=0)),
                ('max_length', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Chains',
                'ordering': ['title'],
                'verbose_name': 'Chain',
            },
        ),
        migrations.CreateModel(
            name='ChainRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('action', models.BooleanField(db_index=True, default=False)),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='journal.Chain')),
            ],
            options={
                'verbose_name_plural': 'Chain Records',
                'ordering': ['-date'],
                'verbose_name': 'Chain Record',
            },
        ),
        migrations.AlterUniqueTogether(
            name='chainrecord',
            unique_together=set([('date', 'chain')]),
        ),
    ]
