# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-16 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_auto_20170627_1704'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chainrecord',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='chainrecord',
            name='chain',
        ),
        migrations.DeleteModel(
            name='Chain',
        ),
        migrations.DeleteModel(
            name='ChainRecord',
        ),
    ]
