# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('email', models.EmailField(max_length=256, unique=True)),
                ('short_bio', models.CharField(max_length=256)),
                ('long_bio', models.CharField(blank=True, max_length=1024, unique=True)),
                ('profile_pic', models.URLField(blank=True, max_length=256, null=True)),
            ],
            options={
                'verbose_name_plural': 'Authors',
                'verbose_name': 'Author',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, unique=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('slug', models.SlugField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Tags',
                'verbose_name': 'Tag',
                'ordering': ['name'],
            },
        ),
    ]
