# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-29 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitebase', '0003_auto_20160214_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True)),
                ('timestamp', models.DateField(auto_now_add=True, db_index=True)),
                ('text', models.TextField()),
                ('user', models.TextField()),
                ('category', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('title', models.CharField(blank=True, db_index=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Feedback',
                'ordering': ['-pk'],
                'verbose_name_plural': 'Feedbacks',
            },
        ),
    ]
