# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sitebase', '0002_auto_20160206_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=128)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_published', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('date_updated', models.DateTimeField()),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('short_description', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('body_type', models.CharField(choices=[('default', 'textarea'), ('html', 'html'), ('markdown', 'markdown')], default='markdown', max_length=8)),
                ('body', models.TextField()),
                ('headerimage', models.URLField(blank=True, max_length=256, null=True)),
                ('highlight', models.BooleanField(default=False)),
                ('authors', models.ManyToManyField(to='sitebase.Author')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
            },
        ),
        migrations.CreateModel(
            name='BlogSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=128)),
                ('short_description', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Blog Series',
                'verbose_name_plural': 'Blog Series',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='series',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.BlogSeries'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(to='sitebase.Tag'),
        ),
    ]
