# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-09 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeX', '0004_auto_20160329_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifexexperiment',
            name='rating',
            field=models.IntegerField(choices=[(5, 'SCORE-5'), (4, 'SCORE-4'), (3, 'SCORE-3'), (2, 'SCORE-2'), (1, 'SCORE-1'), (0, 'NONE')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='lifexidea',
            name='retry',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='lifexidea',
            name='tried',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
