# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-14 07:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lifeX', '0005_auto_20160409_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifeXGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('short_description', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lifeX.LifeXGoal')),
            ],
        ),
    ]
