# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-14 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifeX', '0006_lifexgoal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lifexgoal',
            options={'ordering': ['title'], 'verbose_name': 'LifeX Goal', 'verbose_name_plural': 'LifeX Goals'},
        ),
        migrations.AlterField(
            model_name='lifexgoal',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
