# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GNIBAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('booked', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('category', models.CharField(choices=[('Study', 'GNIB Study Appointment'), ('Work', 'GNIB Work Appointment'), ('Other', 'GNIB Other Appointment')], db_index=True, max_length=8)),
                ('category_type', models.CharField(choices=[('New', 'GNIB New Appointment'), ('Renewal', 'GNIB Renewal Appointment')], db_index=True, max_length=8)),
            ],
            options={
                'verbose_name_plural': 'GNIB Appointments',
                'verbose_name': 'GNIB Appointment',
            },
        ),
        migrations.CreateModel(
            name='VisaAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('booked', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('category', models.CharField(choices=[('I', 'Visa Individual Appointment'), ('F', 'Visa Family Appointment')], db_index=True, max_length=8)),
            ],
            options={
                'verbose_name_plural': 'Visa Appointments',
                'verbose_name': 'Visa Appointment',
            },
        ),
    ]
