# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_apiresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(db_index=True, max_length=64)),
                ('apppointment_gnib', models.CharField(blank=True, choices=[('GSN', 'Study New'), ('GSR', 'Study Renewal'), ('GWN', 'Work New'), ('GWR', 'Work Renewal'), ('GON', 'Other New'), ('GOR', 'Other Renewal')], db_index=True, max_length=64, null=True)),
                ('gnib_filter_date_start', models.DateField(blank=True, null=True)),
                ('gnib_filter_date_end', models.DateField(blank=True, null=True)),
                ('apppointment_visa', models.CharField(blank=True, choices=[('VI', 'Individual'), ('VF', 'Family')], db_index=True, max_length=64, null=True)),
                ('visa_filter_date_start', models.DateField(blank=True, null=True)),
                ('visa_filter_date_end', models.DateField(blank=True, null=True)),
                ('first_interaction', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_interaction', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'ordering': ['chat_id'],
            },
        ),
    ]
