# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_telegramuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='id',
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='chat_id',
            field=models.CharField(db_index=True, max_length=64, primary_key=True, serialize=False),
        ),
    ]
