# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 06:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_auto_20171213_0622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegramuser',
            old_name='apppointment_gnib',
            new_name='appointment_gnib',
        ),
        migrations.RenameField(
            model_name='telegramuser',
            old_name='apppointment_visa',
            new_name='appointment_visa',
        ),
    ]
