# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 07:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_auto_20171213_0636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='first_interaction',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='last_interaction',
        ),
    ]
